### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by errogaht** [JetBrains/youtrack-confluence-plugin#1]
Hello!, universal plugin manager in confluence want to eat .jar file of plugin, and i can understand how get in from all files you placed< please help!

**Comment by steve-todorov** [comment]
Thank you for this plugin! I was also wondering how to install this and if it's still working for confluence 5.6?

**Comment by rayshade** [comment]
Hello, you can skype me and I'll help with this.

**Comment by lequang** [comment]
Hi Egor, what is your skype name?

**Comment by rayshade** [comment]
egor.malyshev

**Comment by rayshade** [comment]
Right now you can just get it from Atlassian Marketplace: https://marketplace.atlassian.com/plugins/youtrack.integration.plugin
