### ISSUE TITLE
JavaScript error in macro browser for the Report macro

### ISSUE THREAD

**Issue by cjberg** [JetBrains/youtrack-confluence-plugin#10]
Since the last update, Confluence's macro browser fails displaying the Report macro *editor* due to a JavaScript error:

`Uncaught TypeError: Cannot read property 'name' of nullbatch.js?locale=en-GB&hostenabled=true&isAdmin=true:778 makeParameterDivbatch.js?locale=en-GB&hostenabled=true&isAdmin=true:561 (anonymous function)batch.js?build-number=5639&locale=en-GB:23 j.extend.eachbatch.js?build-number=5639&locale=en-GB:16 j.fn.j.eachbatch.js?locale=en-GB&hostenabled=true&isAdmin=true:560 loadMacroInBrowser`

It happens both when inserting a new macro or when editing an existing macro on a page. I think it can be related to faulty metadata in `atlassian-plugin.xml`, but I could be wrong.

**Comment by rayshade** [comment]
You were right, there was incorrect metadata in the descriptor, and a NPE in the macro execute method that only occurred when it was open in the editor. Both these are now fixed, and the update has been published to plugin Marketplace page.

**Comment by cjberg** [comment]
Thanks! Confirmed to be working here as well.
