### ISSUE TITLE
.CommandExecutionException: Command failed

### ISSUE THREAD

**Issue by s3ncha** [JetBrains/youtrack-confluence-plugin#11]
Hi,

I've installed plugin and set it up to connect to our youtrack REST api. "Allow all origins" is enabled in Youtrack REST settings and I checked that API works ok using specified user.

I'm adding macro in confluence {issue:id=xx-100} and when I preview or save it, it displays:

issue: youtrack.exceptions.CommandExecutionException: Command failed: GetProject{itemId='xx'} null

Any help to would be highly appreciated. 

Alex

**Comment by rayshade** [comment]
Hello, which plugin version did you install?

**Comment by s3ncha** [comment]
Hi, it's  1.6.8.7

**Comment by rayshade** [comment]
And you configured it properly? I am asking because this exception can
occur  if configuration is wrong or account you specify doesn't have enough
rights for issues you're trying to access.

**Comment by s3ncha** [comment]
Yes I tried using different accounts and getting the same error all the time

**Comment by rayshade** [comment]
And your host address in config looks like what?


On Mon, May 25, 2015 at 3:16 PM, s3ncha <notifications@github.com> wrote:

> Yes I tried using different accounts and getting the same error all the
> time
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/11#issuecomment-105223815>
> .
>



-- 

Call me now please!

**Comment by s3ncha** [comment]
I tried both localhost and local ip.
http://127.0.0.1:81/rest
http://127.0.0.1:81
http://192.168.2.13:81
http://192.168.2.13:81/rest

**Comment by rayshade** [comment]
Try appending / at the end of rest address?

**Comment by s3ncha** [comment]
ah! that fixed it. should have thought about that

**Comment by rayshade** [comment]
I will make a fix to append it if missed. Thanks for bringing this up ☺

**Comment by rayshade** [comment]
I've published 1.6.8.9 where / is appended at the end of REST address on
the configuration page if you don't specify it.

On Mon, May 25, 2015 at 7:51 PM, Egor Malyshev <egor.malyshev@gmail.com>
wrote:

> I will make a fix to append it if missed. Thanks for bringing this up [image:
> ☺]
> On May 25, 2015 7:49 PM, "s3ncha" <notifications@github.com> wrote:
>
>> ah! that fixed it. should have thought about that
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/11#issuecomment-105266156>
>> .
>>
>


-- 

Call me now please!

**Comment by s3ncha** [comment]
thanks again

**Comment by rayshade** [comment]
It's publicly available in 1.7.0.0 version.
