### ISSUE TITLE
Enhancement. Possibility to display additional fields

### ISSUE THREAD

**Issue by s3ncha** [JetBrains/youtrack-confluence-plugin#12]
Hello,

I'm wondering if it would be possible to display additional fields in "detailed" (or some new) mode?
For example, to show current status of the issue, or build number associated with it and etc.

Alex

**Comment by rayshade** [comment]
Sure. I'll make a prototype tomorrow.

**Comment by rayshade** [comment]
So I cooked a build tonight :) I'll double check it first thing tomorrow to
make sure it's OK and will send it to you.

In this build I've added the third style for the link macro: *custom*.

With it you can specify the template for rendering the link text via *template
*parameter.

I've used Velocity for that, so the parameter can contain pretty much any
markup you'd like to render. Plus, all the issue fields are exposed as
variables, so you can use *$summary *to insert issue summary,
*$reporterName* to insert reporter name and so on. This should give you
more freedom in what you need to display as the link text.

I am not sure if you need this or not, but I can make a competely
customizable macro where you would be able to provide a velocity template
to render everything as you want, not only the link text.

If you feel like you need this functionality as well, let me know, I'll add
it.

Also I'm working on adding the custom templates to the report macro so that
it would become more flexible with the possiblity to control what and how
is rendered.

On Tue, May 26, 2015 at 9:39 PM, Egor Malyshev <egor.malyshev@gmail.com>
wrote:

> Sure. I'll make a prototype tomorrow.
> On May 26, 2015 9:37 PM, "s3ncha" <notifications@github.com> wrote:
>
>> Hello,
>>
>> I'm wondering if it would be possible to display additional fields in
>> "detailed" (or some new) mode?
>> For example, to show current status of the issue, or build number
>> associated with it and etc.
>>
>> Alex
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12>.
>>
>


-- 

Call me now please!

**Comment by s3ncha** [comment]
Egor, this is awesome. I'll give it a try today.
Спасибо ;-)

**Comment by s3ncha** [comment]
I was downloading builds from Atlassian website, are your latest builds available somewhere?

**Comment by rayshade** [comment]
​Nope, I only publish them to Marketplace.

Here's the latest version that supports link text customization, I uploaded
it like seconds ago :)

https://marketplace.atlassian.com/plugins/youtrack.integration.plugin/versions#b10900
​

The concept changed slightly, there is no custom mode, just a parameter
that is called *link-text-template *that is a Velocity string. It defaults
to $issue which produces issue id, but you can customize it in any way
using issue fields exposed as variables.

It's supported both for detailed and short mode.

On Wed, May 27, 2015 at 12:19 PM, Alex Sibilev <notifications@github.com>
wrote:

> I was downloading builds from Atlassian website, are your latest builds
> available somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-105835355>
> .
>



-- 

Call me now please!

**Comment by s3ncha** [comment]
Great thanks

**Comment by s3ncha** [comment]
Just tested it. It's working great. Couple of things:
1) line-through css applied to whole template if the issue is closed. (same in detailed mode for text in round brackets)
2) I can't figure out what variable to use or how to specify it in velocity template for fields that contain multiple words. I.e.  $State, $Client work ok, but I can't get "$Fixed in Build" to work
3) This one is nothing to do with your plugin, just wondering if it's possible to save that macro as a template or smth. like this so end users just have to type issue number and it will use predefined velocity template

**Comment by rayshade** [comment]
1) Yes, that's how it is intended to work. I think that maybe I need to add
a parameter like "cross resolved issues" or something like that to control
it.

2) Some of the custom fields are not available via REST and therefore can't
be used in this macro. I'll talk to YouTrack team about that to get more
details.

3) I am not sure if I get this right, but if you're talking about applying
the macro to text that matches a specific pattern (e.g. like id
RSRP-44000), then it's not possible in Confluence.

On Wed, May 27, 2015 at 2:31 PM, Alex Sibilev <notifications@github.com>
wrote:

> Just tested it. It's working great. Couple of things:
> 1) line-through css applied to whole template if the issue is closed.
> (same in detailed mode for text in round brackets)
> 2) I can't figure out what variable to use or how to specify it in
> velocity template for fields that contain multiple words. I.e. $State,
> $Client work ok, but I can't get "$Fixed in Build" to work
> 3) This one is nothing to do with your plugin, just wondering if it's
> possible to save that macro as a template or smth. like this so end users
> just have to type issue number and it will use predefined velocity template
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-105878570>
> .
>



-- 

Call me now please!

**Comment by s3ncha** [comment]
Thanks for response.

Re 3)  I guess what I'm after is for me to create a custom macro with 
with  link-text-template already set to  for example "$summary Status: $State Client: $Client "
so when other confluence users use it they don't have to insert link-text-template themselves

**Comment by rayshade** [comment]
That can be accomplished. You can create a simple macro with code like this:

## @param issue:title=issue|type=string|required=true|desc=Issue id

$action.getHelper().renderConfluenceMacro("{issue:id=$paramissue|link-text-template=Issue:
$issue Reported by: $reporterName}")

Name it like, issue-wrapper, and then you can use it instead like this:

{issue-wrapper:id=DOC-3202}

It will just invoke the original macro with a link-text-template you
specify, and people won't have to type it every time in code.

On Wed, May 27, 2015 at 3:53 PM, Alex Sibilev <notifications@github.com>
wrote:

> Thanks for response.
>
> Re 3) I guess what I'm after is for me to create a custom macro with
> with link-text-template already set to for example "$summary Status:
> $State Client: $Client "
> so when other confluence users use it they don't have to insert
> link-text-template themselves
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-105895352>
> .
>



-- 

Call me now please!

**Comment by s3ncha** [comment]
Great! Thanks for your help.
Will you be adding an option so only issue# is displayed with line-through? :)

**Comment by rayshade** [comment]
In about half hour ☺

**Comment by rayshade** [comment]
https://marketplace.atlassian.com/plugins/youtrack.integration.plugin/versions#b10910

in this version you can specify *strikethru-resolved *parameter that takes
these values:

*all* strikes thru entire link text
*issueId *strikes thru only issue id (default)
*none *this is kinda self-explanatory :)



On Wed, May 27, 2015 at 5:40 PM, Egor Malyshev <egor.malyshev@gmail.com>
wrote:

> In about half hour [image: ☺]
> On May 27, 2015 4:54 PM, "Alex Sibilev" <notifications@github.com> wrote:
>
>> Great! Thanks for your help.
>> Will you be adding an option so only issue# is displayed with
>> line-through? :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-105919986>
>> .
>>
>


-- 

Call me now please!

**Comment by s3ncha** [comment]
sweet! thanks for all your efforts.

**Comment by rayshade** [comment]
:) enjoy

On Wed, May 27, 2015 at 7:42 PM, Alex Sibilev <notifications@github.com>
wrote:

> sweet! thanks for all your efforts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-105988540>
> .
>



-- 

Call me now please!

**Comment by s3ncha** [comment]
stirkethru working a treat :)
can't get my head round how to get rid of extra line breaks when using user macro like you suggested above. It seems that confluence wraps it in extra <p></p>  :(

**Comment by rayshade** [comment]
This might be helpful?
http://stackoverflow.com/questions/10301877/inline-confluence-user-macro​

On Thu, May 28, 2015 at 2:41 AM, Alex Sibilev <notifications@github.com>
wrote:

> stirkethru working a treat :)
> can't get my head round how to get rid of extra line breaks when using
> user macro like you suggested above. It seems that confluence wraps it in
> extra
>
> :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/12#issuecomment-106110416>
> .
>



-- 

Call me now please!
