### ISSUE TITLE
Macro `issue` isn't rendered

### ISSUE THREAD

**Issue by evil-shrike** [JetBrains/youtrack-confluence-plugin#13]
I've installed the latest version of the add-on (1.7.0.3) into Confluence 5.7.1 with Questions (2.0.10).
Then configured it specifying rest url ("http://domain.org/rest/" and user/password).
But Confluence won't render `issue` macro:

```
{issue:id=WC-1026}
```

renders as plain text.
All modules of the add-on are enabled.

What can be wrong?

**Comment by rayshade** [comment]
Any errors in Confluence logs?

**Comment by evil-shrike** [comment]
I can't see any errors (looking here: $confluence_data\logs\atlassian-confluence.log)

**Comment by rayshade** [comment]
What about other custom macros? Are they displayed alright?

**Comment by evil-shrike** [comment]
In macro browser I have only one - code macro. it's a bit strange indeed..

**Comment by rayshade** [comment]
Tried clean installation of 5.7.1 and Questions with plugin 1.7.0.3, works good. Maybe there's some issue with confluence user permissions?

**Comment by evil-shrike** [comment]
well something wrong with my Confluence, tried to reinstall the add-on and found this in log:
```
2015-07-20 22:39:15,357 INFO [http-bio-10.20.12.102-83-exec-10] [atlassian.plugin.manager.DefaultPluginManager] disableDependentPlugins Found dependent enabled plugins for uninstalled plugin 'youtrack.integration.plugin': [].  Disabling...

2015-07-20 22:39:15,357 INFO [http-bio-10.20.12.102-83-exec-10] [atlassian.plugin.manager.DefaultPluginManager] notifyPluginDisabled Disabling youtrack.integration.plugin
```

**Comment by rayshade** [comment]
The plugin depends on the following components:

`<component-import key="userManager" interface="com.atlassian.sal.api.user.UserManager"/>`
`<component-import key="loginUriProvider" interface="com.atlassian.sal.api.auth.LoginUriProvider"/>`
`<component-import key="renderer" interface="com.atlassian.templaterenderer.velocity.one.six.VelocityTemplateRenderer"/>`
`<component-import key="pluginSettingsFactory" interface="com.atlassian.sal.api.pluginsettings.PluginSettingsFactory"/>`
`<component-import key="transactionTemplate" interface="com.atlassian.sal.api.transaction.TransactionTemplate"/>`
`<component-import key="applicationProperties" interface="com.atlassian.sal.api.ApplicationProperties"/>`

**Comment by Elishtar** [comment]
Hello Sergei, if you use youtrack plugin at this moment and have some issue, please report it to http://youtrack.jetbrains.com

Template for report:
https://youtrack.jetbrains.com/newIssue?project=JT&c=State%20Open&c=Assignee%20Andrey.Klyuev&c=Subsystem%20Integrations
