### ISSUE TITLE
Feature: Confluence cloud marketplace support

### ISSUE THREAD

**Issue by Nickplicity** [JetBrains/youtrack-confluence-plugin#22]
From what I can gather, this plugin only supports confluence server installations. Can you please confirm this?

If this is correct, can this be extended to support confluence cloud. 

I am confident the majority of new confluence instances are being set-up in the cloud so this is where the customers like me are.

Alternatively, a comment on why this might not be simple would also be valuable.

Thanks

**Comment by Elishtar** [comment]
Hello Nick, unfortunately at this moment, we can't give support cloud version, but we try to do this in the future. You can vote for this feature here https://youtrack.jetbrains.com/issue/JT-32837
