### ISSUE TITLE
Support for "Tags" as a column in the report macro

### ISSUE THREAD

**Issue by pjohnkeane** [JetBrains/youtrack-confluence-plugin#23]
I'd like to be able to add "Tags" as a column in the report macro -- currently if I add a column with this name, the report just returns ? for each issue. I was hoping that given this works for csv export from YT, it might "just work"... :)

I'd also like fields containing a sequence (e.g. if an issue is assigned to multiple people) to return a comma-separated list (again, as in the csv export).

**Comment by Elishtar** [comment]
Hello, thank you for your request, please use this function in version 1.8.1.5
