### ISSUE TITLE
Display period-type fields as periods rather than minutes in the report macro

### ISSUE THREAD

**Issue by pjohnkeane** [JetBrains/youtrack-confluence-plugin#24]
I'm using the report macro to provide a summary of issues included in a sprint (for example) and I include _Spent time_ as a column to return time tracking data against each issue. 

This is a period field, displayed as e.g. 1d2h30m in YT, but it's returned in minutes in the report macro (e.g. 570). 

Given that the audience for my summary is often my wider stakeholders (rather than team members), formatting the time spent in this way is unhelpful. Is there any possibility of returning it formatted as per the YT UI?

**Comment by Elishtar** [comment]
Hello, if you use plugin on this moment, please update to version 1.8.1.3 
![image](https://user-images.githubusercontent.com/989215/53083676-6dd5fc80-3510-11e9-8a02-22d50848b6f3.png)
