### ISSUE TITLE
Configurable defaults

### ISSUE THREAD

**Issue by REDLINK** [JetBrains/youtrack-confluence-plugin#25]
Would it be possible to add plugin configuration settings to change the global defaults for style, strikethru-resolved and link-text-template? My colleagues often forget to use the correct settings.

**Comment by Elishtar** [comment]
Hello, very good request, it will be implemented in the next release(Feb 2019).
If you have any other ideas please create a task like showed on plugin page(More details).

Template to create the pull request
https://youtrack.jetbrains.com/newIssue?project=JT&c=State%20Open&c=Assignee%20Andrey.Klyuev&c=Subsystem%20Integrations

**Comment by Elishtar** [comment]
Implemented in version 1.8.1.2
https://marketplace.atlassian.com/apps/1213094/youtrack-integration?hosting=server&tab=versions
