### ISSUE TITLE
Display date-type fields as dates in the report macro

### ISSUE THREAD

**Issue by pjohnkeane** [JetBrains/youtrack-confluence-plugin#26]
I'd like to include date-type fields in issue reports (date added to sprint, resolved date, due date, etc) but when fields of this type are added as columns to the report macro, the output uses (I think) a unix datestamp, like 1547726400000.

**Comment by lehvolk** [comment]
Fixed in 536d99ca2f424c3c0c1c68149275b1fb3523a3c5
