### ISSUE TITLE
Support for 5.7?

### ISSUE THREAD

**Issue by jonaslaberg** [JetBrains/youtrack-confluence-plugin#3]
Hi, would love to install this plugin. We're upgrading to confluence 5.7 these days - would it work with that version?

**Comment by rayshade** [comment]
Should work. I will try it with 5.7 today

**Comment by jonaslaberg** [comment]
Great, thanks!

**Comment by rayshade** [comment]
Looks like it's OK with 5.7 so far

On Wed, Feb 18, 2015 at 12:09 PM, jonaslaberg <notifications@github.com>
wrote:

> Great, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/3#issuecomment-74833145>
> .
>



-- 

Call me now please!

**Comment by jonaslaberg** [comment]
Good news, thanks for that!

**Comment by rayshade** [comment]
​You're welcome. If you need anything fixed or added in the plugin, drop me
a message, and we'll discuss it :)​

On Wed, Feb 18, 2015 at 4:39 PM, jonaslaberg <notifications@github.com>
wrote:

> Good news, thanks for that!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/3#issuecomment-74864713>
> .
>



-- 

Call me now please!

**Comment by jonaslaberg** [comment]
Thanks for the offer, will do!
