### ISSUE TITLE
Fatal error using master and YouTrack 6

### ISSUE THREAD

**Issue by tetsuo13** [JetBrains/youtrack-confluence-plugin#4]
This is more of a note since the 5.6.1-api branch is the future of this plugin and there aren't any issues there with YouTrack 6 compatibility but I wanted to at least document the issue as I've found it.

The plugin compiled using the master branch at c17b0baf40478d9f96fc143e3836a04441b0a40f does not work with YouTrack 6, Confluence showed a fatal error when rendering the plugin. I was previously using YouTrack 5 with no issues. I had to use `YouTrackRestApi.jar` from the 5.6.1-api branch at faeb40d0206eb4376ffb007ab59108e2c7dad5df and make some adjustments to `IssueHighlighter.java` in order to use its newer API.

The rayshade/YouTrackRestApi project isn't using tags but it would be helpful to know in this project at which commit hash the `YouTrackRestApi.jar` file references. Going between master and 5.6.1-api I had no way of knowing what API changes to expect and had to use the methods in 5.6.1-api as reference.

**Comment by rayshade** [comment]
I've merged the branches and since now it's always uses YouTrack API from the latest commit to that repository.
