### ISSUE TITLE
Non-ANSI characters render incorrectly

### ISSUE THREAD

**Issue by cjberg** [JetBrains/youtrack-confluence-plugin#7]
While testing the plugin I discovered it renders YouTrack issues having non-ANSI (Swedish) characters in the summary description incorrectly. Any such character is displayed as two nonsensical characters, as it typically is if one takes UTF-8 encoded data and by mistake treat it as for instance ISO-8859-1 or Windows-1252.

Both macros have the same issue, so I'm guessing there is some error in the base class. It requests and gets UTF-8 from YouTrack, but it looks like it doesn't decode it properly.

YouTrack: 6.0 build 12634
Confluence: 5.6.6

(By the way, this is an exciting initiative. My company has been using Confluence for a long time and just recently begun using YouTrack, so I'm really happy to be able to integrate the two easily. Thanks!)

**Comment by rayshade** [comment]
Thanks for telling me about this. Will fix asap ☺

**Comment by rayshade** [comment]
I've just published a new version to Atlassian Marketplace, it contains the
fix for incorrect Unicode handling (tested it on my local installation.)
Hope this will work for you, too :)

On Mon, Mar 16, 2015 at 11:10 PM, Egor Malyshev <egor.malyshev@gmail.com>
wrote:

> Thanks for telling me about this. Will fix asap ☺
> On Mar 16, 2015 10:24 PM, "C-J Berg" <notifications@github.com> wrote:
>
>> While testing the plugin I discovered it renders YouTrack issues having
>> non-ANSI (Swedish) characters in the summary description incorrectly. Any
>> such character is displayed as two nonsensical characters, as it typically
>> is if one takes UTF-8 encoded data and by mistake treat it as for instance
>> ISO-8859-1 or Windows-1252.
>>
>> Both macros have the same issue, so I'm guessing there is some error in
>> the base class. It requests and gets UTF-8 from YouTrack, but it looks like
>> it doesn't decode it properly.
>>
>> YouTrack: 6.0 build 12634
>> Confluence: 5.6.6
>>
>> (By the way, this is an exciting initiative. My company has been using
>> Confluence for a long time and just recently begun using YouTrack, so I'm
>> really happy to be able to integrate the two easily. Thanks!)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/7>.
>>
>


-- 

Call me now please!

**Comment by cjberg** [comment]
Wow, fastest fix of a Confluence plugin ever? **Awesome!** I've tested it now and I can verify that it works for me as well.

I noticed two things:
* I think you left a `System.out.println` by mistake in `IssueLink`'s execute method?
* I believe it's better to exclude `.idea\workspace.xml` from version control (see [How to manage projects under VCS](https://intellij-support.jetbrains.com/entries/23393067-How-to-manage-projects-under-Version-Control-Systems)). It's a user specific file that changes every time you work in one of your IDEs, so every commit will be "polluted" by it for no good reason. You can add it to `.gitignore`, then untrack it with `git rm --cached .idea\workspace.xml`, and finally `git add -u; git commit -m 'Untracked and ignored .idea\workspace.xml'` (in a clean workspace, that is).

**Comment by rayshade** [comment]
Oops, my bad. Removed the println, and also now the link style in issue macro is a drop-down with all possible values. It's now published in version 1.6.8.3

The workspace.xml was on my ignored files list, strange that it did go. Looks like your solution helped to remove it, thanks for pointing that out.
