### ISSUE TITLE
Suggestion: Improved discoverability for macro settings

### ISSUE THREAD

**Issue by cjberg** [JetBrains/youtrack-confluence-plugin#8]
Using Confluence 5.x macros are usually configured in a modal dialog. Currently the dialog simply displays two text fields for "id" and "style". While "id" was obvious, I had to resort to looking at the source code for finding out the other possible value: "short" (default) and "detailed". Very few of my peers would be able to do that (not developers). It would be preferable to see a drop-down of the available settings.

It would also be nice to see the plug-in make use of YouTrack's REST interface for listing available projects and perhaps issues and/or saved queries as well.

I know this is an early version of the plug-in, so I'm simply suggesting future improvements. Thanks!

**Comment by rayshade** [comment]
Yes, these are good suggestions. I will be looking into the improvements
for the macro insertion editor integrations in a while. Right now I am
developing some more macros and thinking about a way to make the report
AJAX based so that it wouldn't need to reload the entire page when you're
browsing thru issue pages.

On Mon, Mar 16, 2015 at 10:38 PM, C-J Berg <notifications@github.com> wrote:

> Using Confluence 5.x macros are usually configured in a modal dialog.
> Currently the dialog simply displays two text fields for "id" and "style".
> While "id" was obvious, I had to resort to looking at the source code for
> finding out the other possible value: "short" (default) and "detailed".
> Very few of my peers would be able to do that (not developers). It would be
> preferable to see a drop-down of the available settings.
>
> It would also be nice to see the plug-in make use of YouTrack's REST
> interface for listing available projects and perhaps issues and/or saved
> queries as well.
>
> I know this is an early version of the plug-in, so I'm simply suggesting
> future improvements. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/youtrack-confluence-plugin/issues/8>.
>



-- 

Call me now please!

**Comment by cjberg** [comment]
Thanks for improving this already! I noticed other plugins display parameter labels with proper casing, for instance, "id" could be displayed as "Issue ID". Looking around I found this is achieved by using the i18n files (meaning you could support different languages as well in the future).

Here's a macro plugin tutorial on BitBucket that includes the i18n configuration for a parameter's label and description: [Macro Magic](https://bitbucket.org/resah/confluence-macro-tutorial/wiki/Home)

**Comment by rayshade** [comment]
Good doc, I'll have a look at it.

**Comment by Elishtar** [comment]
Hello, thank you for your advice. If you use youtrack plugin at this moment and have some issue report it to https://youtrack.jetbrains.com

Template to create the pull request
https://youtrack.jetbrains.com/newIssue?project=JT&c=State%20Open&c=Assignee%20Andrey.Klyuev&c=Subsystem%20Integrations
